apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: eg2sm42xl-java-quarkus-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/eg2sm42xl-java-quarkus-gitops